//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itenso.Solutions.Community.Commands.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itenso.Solutions.Community.Commands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Information.
        /// </summary>
        internal static string CommandApplicationAboutDescription {
            get {
                return ResourceManager.GetString("CommandApplicationAboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string CommandApplicationAboutText {
            get {
                return ResourceManager.GetString("CommandApplicationAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Program.
        /// </summary>
        internal static string CommandApplicationShutdownDescription {
            get {
                return ResourceManager.GetString("CommandApplicationShutdownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string CommandApplicationShutdownText {
            get {
                return ResourceManager.GetString("CommandApplicationShutdownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Font Family.
        /// </summary>
        internal static string CommandChangeFontFamilyDescription {
            get {
                return ResourceManager.GetString("CommandChangeFontFamilyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+F.
        /// </summary>
        internal static string CommandChangeFontFamilyGestures {
            get {
                return ResourceManager.GetString("CommandChangeFontFamilyGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        internal static string CommandChangeFontFamilyText {
            get {
                return ResourceManager.GetString("CommandChangeFontFamilyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Command Statistics.
        /// </summary>
        internal static string CommandCommandStatisticsDescription {
            get {
                return ResourceManager.GetString("CommandCommandStatisticsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Statistics.
        /// </summary>
        internal static string CommandCommandStatisticsText {
            get {
                return ResourceManager.GetString("CommandCommandStatisticsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink Font.
        /// </summary>
        internal static string CommandDecreaseFontSizeDescription {
            get {
                return ResourceManager.GetString("CommandDecreaseFontSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        internal static string CommandDecreaseFontSizeText {
            get {
                return ResourceManager.GetString("CommandDecreaseFontSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Text Indent.
        /// </summary>
        internal static string CommandDecreaseIndentationDescription {
            get {
                return ResourceManager.GetString("CommandDecreaseIndentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Indent.
        /// </summary>
        internal static string CommandDecreaseIndentationText {
            get {
                return ResourceManager.GetString("CommandDecreaseIndentationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo the last action.
        /// </summary>
        internal static string CommandEditRedoDescription {
            get {
                return ResourceManager.GetString("CommandEditRedoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Y.
        /// </summary>
        internal static string CommandEditRedoGestures {
            get {
                return ResourceManager.GetString("CommandEditRedoGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string CommandEditRedoText {
            get {
                return ResourceManager.GetString("CommandEditRedoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo the last action.
        /// </summary>
        internal static string CommandEditUndoDescription {
            get {
                return ResourceManager.GetString("CommandEditUndoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Z.
        /// </summary>
        internal static string CommandEditUndoGestures {
            get {
                return ResourceManager.GetString("CommandEditUndoGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string CommandEditUndoText {
            get {
                return ResourceManager.GetString("CommandEditUndoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grow Font.
        /// </summary>
        internal static string CommandIncreaseFontSizeDescription {
            get {
                return ResourceManager.GetString("CommandIncreaseFontSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        internal static string CommandIncreaseFontSizeText {
            get {
                return ResourceManager.GetString("CommandIncreaseFontSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Text Indent.
        /// </summary>
        internal static string CommandIncreaseIndentationDescription {
            get {
                return ResourceManager.GetString("CommandIncreaseIndentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Indent.
        /// </summary>
        internal static string CommandIncreaseIndentationText {
            get {
                return ResourceManager.GetString("CommandIncreaseIndentationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Font Bold-Weight.
        /// </summary>
        internal static string CommandToggleBoldDescription {
            get {
                return ResourceManager.GetString("CommandToggleBoldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+B.
        /// </summary>
        internal static string CommandToggleBoldGestures {
            get {
                return ResourceManager.GetString("CommandToggleBoldGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string CommandToggleBoldText {
            get {
                return ResourceManager.GetString("CommandToggleBoldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Font Italic-Style.
        /// </summary>
        internal static string CommandToggleItalicDescription {
            get {
                return ResourceManager.GetString("CommandToggleItalicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+I.
        /// </summary>
        internal static string CommandToggleItalicGestures {
            get {
                return ResourceManager.GetString("CommandToggleItalicGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string CommandToggleItalicText {
            get {
                return ResourceManager.GetString("CommandToggleItalicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Font Underline-Decoration.
        /// </summary>
        internal static string CommandToggleUnderlineDescription {
            get {
                return ResourceManager.GetString("CommandToggleUnderlineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+U.
        /// </summary>
        internal static string CommandToggleUnderlineGestures {
            get {
                return ResourceManager.GetString("CommandToggleUnderlineGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string CommandToggleUnderlineText {
            get {
                return ResourceManager.GetString("CommandToggleUnderlineText", resourceCulture);
            }
        }
    }
}
